apiVersion: "v1"
kind: Pod
metadata:
  name: web-pod
  labels:
    name: web
    env: dev
spec:
  containers:
    - name: hello-node
      image: hello-node:v1
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP